FROM python:3.9-alpine

RUN apk add --no-cache --virtual .build-deps \
    build-base \
  && apk add --no-cache \
    bash \
  && pip install --upgrade pip \
  && apk del .build-deps

COPY requirements.txt .
RUN python3 -m pip install --prefix=/install -r requirements.txt

WORKDIR /app
COPY import.py entrypoint.sh /app/

ENTRYPOINT ["/app/entrypoint.sh"]
