FROM redhat/ubi9-minimal AS builder

RUN microdnf install -y python3 python3-pip bash \
  && microdnf clean all \
  && rm -rf /var/cache/dnf

WORKDIR /install
COPY requirements.txt .
RUN python3 -m pip install --prefix=/install -r requirements.txt

RUN mkdir /runtime-deps \
  && for bin in /usr/bin/python3 /usr/bin/bash; do \
      for lib in $(ldd $bin | awk '/=>/ {print $(NF-1)}' | grep '^/'); do \
        cp "$lib" /runtime-deps/; \
      done; \
    done \
  && cp /lib64/ld-linux-x86-64.so.2 /runtime-deps/

FROM scratch

COPY --from=builder /usr/bin/bash /bin/bash

COPY --from=builder /usr/bin/python3.9 /usr/bin/python3.9
COPY --from=builder /usr/lib64/python3.9 /usr/lib64/python3.9
COPY --from=builder /usr/lib64/libpython3.9.so.* /usr/lib64/

COPY --from=builder /usr/lib64/python3.9/lib-dynload /usr/lib64/python3.9/lib-dynload

COPY --from=builder /usr/lib64/libz.so.* /usr/lib64/
COPY --from=builder /usr/lib64/libcrypto.so.* /usr/lib64/
COPY --from=builder /usr/lib64/libssl.so.* /usr/lib64/

COPY --from=builder /install /install
COPY --from=builder /runtime-deps/ /lib64/

WORKDIR /app
COPY import.py entrypoint.sh /app/

ENTRYPOINT ["/app/entrypoint.sh"]
